name: proof_concept
channels:
 - conda-forge
 - default
dependencies:
  - numpy=1.21.5
  - matplotlib=3.7.0
  - pandas=1.4.4
  - scikit-learn=1.1.3
  - seaborn=0.12.1
  - scipy=1.7.3
  - joblib=1.1.1
